# Generated by Django 4.0.4 on 2022-04-21 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='tomador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faturamento.tomador'),
        ),
    ]
