# Generated by Django 4.0.4 on 2022-04-21 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_alter_nfe_tomador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomador',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='faturamento.endereco'),
        ),
    ]
