# Generated by Django 4.0.4 on 2022-04-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0006_alter_servico_item_lista_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='natureza_operacao',
            field=models.CharField(max_length=50),
        ),
    ]
