# Generated by Django 4.0.4 on 2022-04-29 15:10

from django.db import migrations, models
import faturamento.models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0007_alter_nfe_natureza_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaComprovada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arquivo', models.FileField(upload_to=faturamento.models.path_file_media)),
                ('upload_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
