# Generated by Django 4.0.4 on 2022-05-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mei', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='CNPJ',
            new_name='cnpj',
        ),
        migrations.AddField(
            model_name='cliente',
            name='mei',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='mei.mei'),
            preserve_default=False,
        ),
    ]
