# Generated by Django 4.0.4 on 2022-05-04 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mei.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mei', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mei.mei')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DespesaComprovada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arquivo', models.FileField(upload_to=mei.models.path_file_media)),
                ('upload_date', models.DateField(auto_now=True)),
                ('mei', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mei.mei')),
            ],
        ),
    ]
